version: '{branch}.{build}'
clone_folder: c:\projects\pocketmine_chunkutils

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.8
  ARCH: x64

  matrix:
    - PHP_VER: 7.0
      VC_VER: vc14
install:
- cmd: cinst wget
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"

    wget https://github.com/OSTC/php-sdk-binary-tools/archive/%PHP_SDK_BINARY_TOOLS_VER%.zip --no-check-certificate -q -O php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip

    7z x -y php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip -oC:\projects

    move C:\projects\php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER% C:\projects\php-sdk

    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    git clone https://github.com/php/php-src C:\projects\php-src -b PHP-%PHP_VER% --depth=1

    mkdir C:\projects\php-src\ext\pocketmine_chunkutils

    xcopy C:\projects\pocketmine_chunkutils C:\projects\php-src\ext\pocketmine_chunkutils /s /e /y /q

    wget http://windows.php.net/downloads/php-sdk/deps-%PHP_VER%-%VC_VER%-%ARCH%.7z -q

    7z x -y deps-%PHP_VER%-%VC_VER%-%ARCH%.7z -oC:\projects\php-src

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --disable-all --enable-cli --enable-zts --enable-pocketmine-chunkutils=shared --with-config-file-scan-dir=C:\projects\pocketmine_chunkutils\bin\modules.d --with-prefix=C:\projects\pocketmine_chunkutils\bin --with-php-build=deps --enable-debug-pack

    nmake

    nmake install

    copy php.ini-development C:\projects\pocketmine_chunkutils\bin\php.ini

    copy C:\projects\php-src\x64\Release_TS\php_pocketmine_chunkutils.pdb C:\projects\pocketmine_chunkutils\bin\ext\php_pocketmine_chunkutils.pdb

    mkdir C:\projects\pocketmine_chunkutils\bin\modules.d

    echo extension=php_pocketmine_chunkutils.dll > C:\projects\pocketmine_chunkutils\bin\modules.d\php.ini
test_script:
- cmd: C:\projects\pocketmine_chunkutils\bin\php.exe -doutput_buffering=0 run-tests.php ext\pocketmine_chunkutils -p C:\projects\pocketmine_chunkutils\bin\php.exe -q --show-diff
artifacts:
  - path: bin\ext
    name: php_pocketmine_chunkutils-%PHP_VER%-%VC_VER%-%ARCH%
    type: zip
